# Generated by Django 3.2.7 on 2024-09-06 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_todotask_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 11, 3, 57, 510, tzinfo=utc)),
        ),
    ]
